/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AudioEngine {
  constructor()
  listDevices(): Array<AudioDevice>
  start(config: AudioStartConfig): void
  stop(): void
  setMode(mode: string): void
  setParams(params: AudioParamsUpdate): void
  getLatestFeatures(): AudioFeatures
  startAnalysisRecording(config: AudioStartConfig): void
  getAnalysisRecordingWaveform(): AnalysisRecordingWaveform
  stopAnalysisRecording(): RawAudioRecording
}

export interface AnalysisRecordingWaveform {
  durationMs: number
  totalSamples: number
  waveform: Array<number>
}

export interface AudioDevice {
  id: string
  name: string
  host: string
  inputChannels: number
  defaultSampleRate: number
  supportedSampleRates: Array<number>
  isDefault: boolean
}

export interface AudioFeatures {
  t: number
  rms: number
  peak: number
  low: number
  mid: number
  high: number
  spectralCentroid: number
  pitchHz?: number
  pitchConfidence: number
  noteName?: string
  noteStability: number
  onset: number
  gate: boolean
  clipping: boolean
  chroma: Array<number>
  spectralFlux: number
  spectralRolloff: number
  spectralFlatness: number
  zeroCrossingRate: number
  brightness: number
  noisiness: number
  attack: number
  decay: number
  bendCents: number
  vibratoDepth: number
  vibratoRate: number
  harmonicDensity: number
  chordRoot?: string
  chordQuality?: string
  chordName?: string
  chordConfidence: number
  logSpectrum: Array<number>
  spectralContrast: number
  harmonicRatio: number
  pickNoise: number
  muteAmount: number
  guitarTechnique: string
  guitarTechniqueConfidence: number
  stringNumber?: number
  fretNumber?: number
  voicing: Array<GuitarVoicingCandidate>
  guitarEvents: Array<GuitarEvent>
}

export interface AudioParamsUpdate {
  inputGain?: number
  gateThreshold?: number
}

export interface AudioStartConfig {
  mode: string
  deviceId?: string
  channelIndex: number
  sampleRate: number
  bufferSize: number
  featureRateHz: number
  inputGain: number
  gateThreshold: number
}

export interface GuitarEvent {
  id: number
  t: number
  type: string
  strength: number
  noteName?: string
  pitchHz?: number
  stringNumber?: number
  fretNumber?: number
  chordName?: string
}

export interface GuitarVoicingCandidate {
  stringNumber: number
  fretNumber: number
  pitchClass: number
  confidence: number
}

export interface RawAudioRecording {
  sampleRate: number
  samples: Array<number>
}
