/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AudioEngine {
  constructor()
  listDevices(): Array<AudioDevice>
  start(config: AudioStartConfig): void
  stop(): void
  setMode(mode: string): void
  setParams(params: AudioParamsUpdate): void
  getLatestFeatures(): AudioFeatures
}

export interface AudioDevice {
  id: string
  name: string
  host: string
  inputChannels: number
  defaultSampleRate: number
  supportedSampleRates: Array<number>
  isDefault: boolean
}

export interface AudioFeatures {
  t: number
  rms: number
  peak: number
  low: number
  mid: number
  high: number
  spectralCentroid: number
  pitchHz?: number
  pitchConfidence: number
  noteName?: string
  noteStability: number
  onset: number
  gate: boolean
  clipping: boolean
  chroma: Array<number>
  spectralFlux: number
  spectralRolloff: number
  spectralFlatness: number
  zeroCrossingRate: number
  brightness: number
  noisiness: number
  attack: number
  decay: number
  bendCents: number
  vibratoDepth: number
  vibratoRate: number
  harmonicDensity: number
  chordRoot?: string
  chordQuality?: string
  chordName?: string
  chordConfidence: number
}

export interface AudioParamsUpdate {
  inputGain?: number
  gateThreshold?: number
}

export interface AudioStartConfig {
  mode: string
  deviceId?: string
  channelIndex: number
  sampleRate: number
  bufferSize: number
  featureRateHz: number
  inputGain: number
  gateThreshold: number
}
