/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AudioEngine {
  constructor()
  listDevices(): Array<AudioDevice>
  start(config: AudioStartConfig): void
  stop(): void
  setMode(mode: string): void
  getLatestFeatures(): AudioFeatures
}

export interface AudioDevice {
  id: string
  name: string
  host: string
  inputChannels: number
  defaultSampleRate: number
  supportedSampleRates: Array<number>
  isDefault: boolean
}

export interface AudioFeatures {
  t: number
  rms: number
  peak: number
  low: number
  mid: number
  high: number
  spectralCentroid: number
  pitchHz?: number
  pitchConfidence: number
  noteName?: string
  noteStability: number
  onset: number
  gate: boolean
  clipping: boolean
}

export interface AudioStartConfig {
  mode: string
  deviceId?: string
  channelIndex: number
  sampleRate: number
  bufferSize: number
  featureRateHz: number
  inputGain: number
  gateThreshold: number
}
